import { execFileSync } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { CodeGraphAdapter } from '../codebase/codegraph-adapter.js';
import { GitWorkspace } from '../codebase/git-workspace.js';
import { authedUrl, commentOnIssue, openIssue, openPullRequest, plainUrl, pushBranch } from '../github/index.js';
import type { Project } from '../projects/index.js';
import type { AIProvider } from '../resolver/ai-provider.js';
import { BugResolver } from '../resolver/bug-resolver.js';
import type { Incident, ResolutionResult } from '../resolver/types.js';

export interface FixJobOptions {
  project: Pick<Project, 'repo' | 'defaultBranch' | 'testCommand' | 'buildCommand'>;
  incident: Incident;
  /** How many customers reported it. No personal data goes to GitHub, only this count. */
  reportCount: number;
  token: string;
  ai: AIProvider;
  /** Overrides github.com for clone and push (tests use a local bare repo). */
  remoteUrl?: string;
  fetch?: typeof fetch;
  /** The GitHub issue this incident lives in: the PR closes it, and a failure is reported on it instead of a new issue. */
  issueNumber?: number;
}

export type FixOutcome =
  | { status: 'pr_opened'; url: string }
  | { status: 'needs_human'; url?: string; reason: string };

const tail = (text: string | undefined, n = 1500) => (text ?? '').trim().slice(-n);

function prBody(result: ResolutionResult, reportCount: number, issueNumber?: number): string {
  const inv = result.investigation!;
  const last = result.attempts[result.attempts.length - 1];
  return [
    `## Incident\n${result.incident.title}\n\nReported by ${reportCount} customer(s).`,
    `## Root cause\n${inv.rootCause}`,
    inv.evidence?.length ? `## Evidence\n${inv.evidence.map((e) => `- ${e}`).join('\n')}` : '',
    `## Fix\n${result.summary}`,
    `## Verification\nTests before the fix: ${result.baseline?.success ? 'passing (the bug was not covered)' : 'failing'}\n` +
      `Tests and build after the fix: passing, attempt ${last.number} of ${result.attempts.length}.\n\n` +
      `<details><summary>Test output after the fix</summary>\n\n\`\`\`\n${tail(last.tests?.output)}\n\`\`\`\n</details>`,
    `## Risk\nGenerated by BlazeResolver (${inv.confidence} confidence). Review the diff. Nothing merges without a human.`,
    issueNumber ? `Closes #${issueNumber}` : ''
  ].filter(Boolean).join('\n\n');
}

/**
 * One incident, start to a GitHub pull request: clone, resolve in isolated workspaces, push a branch, open the PR.
 * When no fix passes, it opens an issue with the findings instead of a PR. It never merges or pushes to the default branch.
 *
 * Tests and builds get a minimal environment, so a repo's own code can't read this server's API keys or token.
 * ponytail: it still runs the repo's code on this machine; that is only safe for repos you trust or inside a container sandbox.
 */
export async function runFix(opts: FixJobOptions): Promise<FixOutcome> {
  const { project, incident, token, ai } = opts;
  const root = mkdtempSync(join(tmpdir(), 'blaze-job-'));
  const repoDir = join(root, 'repo');
  const remote = opts.remoteUrl ?? authedUrl(project.repo, token);
  let codebase: CodeGraphAdapter | undefined;

  try {
    execFileSync('git', ['clone', '--quiet', remote, repoDir], { stdio: 'pipe', env: { ...process.env, GIT_TERMINAL_PROMPT: '0' } });
    // Keep the token out of the clone's config, where the repo's own tests could read it.
    execFileSync('git', ['remote', 'set-url', 'origin', opts.remoteUrl ?? plainUrl(project.repo)], { cwd: repoDir });

    codebase = new CodeGraphAdapter({ root: repoDir });
    const workspaces = new GitWorkspace({
      repo: repoDir,
      baseRef: project.defaultBranch,
      testCommand: project.testCommand,
      buildCommand: project.buildCommand,
      workspacesDir: join(root, 'workspaces'),
      env: { PATH: process.env.PATH, HOME: process.env.HOME, CI: 'true', NODE_ENV: 'test' }
    });
    const result = await new BugResolver({ codebase, workspaces, ai }).resolve(incident);

    if (result.status === 'READY_FOR_REVIEW') {
      const branch = `blazeresolver/fix-${incident.id}`;
      await workspaces.commit(result.workspace!, `fix: ${incident.title}`.slice(0, 200));
      await pushBranch(result.workspace!.path, remote, branch, token);
      const pr = await openPullRequest(
        { token, repo: project.repo, head: branch, base: project.defaultBranch, title: `fix: ${incident.title}`.slice(0, 200), body: prBody(result, opts.reportCount, opts.issueNumber) },
        opts.fetch
      );
      return { status: 'pr_opened', url: pr.url };
    }

    const reason = result.failureReason ?? 'no passing fix';
    const findings =
      `BlazeResolver could not produce a passing fix.\n\n**Incident:** ${incident.title}\n${incident.description}\n\n` +
      `**Reported by:** ${opts.reportCount} customer(s)\n**Why it stopped:** ${reason}\n` +
      (result.investigation ? `\n**Best guess at the cause (${result.investigation.confidence} confidence):** ${result.investigation.rootCause}\n` : '');

    if (opts.issueNumber) {
      await commentOnIssue(token, project.repo, opts.issueNumber, findings, opts.fetch);
      return { status: 'needs_human', url: `https://github.com/${project.repo}/issues/${opts.issueNumber}`, reason };
    }
    const issue = await openIssue(
      { token, repo: project.repo, title: `Customer-reported bug needs a human: ${incident.title}`.slice(0, 200), body: findings },
      opts.fetch
    );
    return { status: 'needs_human', url: issue.url, reason };
  } catch (err) {
    // execFileSync errors quote the whole command, clone URL and token included.
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(token ? message.split(token).join('***') : message);
  } finally {
    await codebase?.close().catch(() => {});
    rmSync(root, { recursive: true, force: true });
  }
}
